RANKING_MAX_NUMBER = 40
STATUS_INVEST_FINANCIAL_CSV_FILENAME = "statusinvest_financas.csv"
STATUS_INVEST_CSV_FILENAME = "statusinvest.csv"

DELIMITER=";"
DECIMAL=","
THOUSANDS="."
INDEX_COL="TICKER"

DAILY_LIQUIDY_COLUMN = ' LIQUIDEZ MEDIA DIARIA'
DAILY_LIQUIDY_MIN_VALUE = 3000000
EBIT_MARGIN_COLUMN = 'MARGEM EBIT'
EBIT_MARGIN_MIN_VALUE = 0

EVEBIT_COLUMN = "EV/EBIT"
ROIC_COLUMN = "ROIC"
